- Caracteristicas
      - pitfalls
        - GIL
          - asyncio
          - redis, celery, etc
          - dask, numpy, tensorflow, cython
        - dinâmico/otimização
          - dificuldade de otimizar compilação
          - nuitka
          - Pypy
          - cálculos vetorizados e Cython
        - na prática, pouco impacto (Pareto)
      - vantagens
        - baterias incluidas
        - pip/conda --> loja de aplicativos
          - (baterias incluidas e acessorios a um clique)
          - venv e modular evita dependency hell
          - rodar pip freeze, criar venv, pip install, update, ==, >=, activate, deactivate, etc.        - import this
        - dinamico
        - conciso e coeso
        - fluidez
        - Porque Python
          - Produtividade
            - maximizar recurso
          - Usabilidade e simplicidade
            - focar no problema de negócio
          - Concisão
            - menos código, menos bugs
          - Recurso humano >> recurso computacional
            - economia inteligente
          - Comunidade
            - Principio de Linus
            - "Mercado"


In [1]:
import random
import time
import numpy as np

In [2]:
s0 = time.time()
lista1 = [random.randint(1, 10) for num in range(10**6)]
lista2 = [random.randint(1, 10) for num in range(10**6)]
lista3 = []
for itemlista1, itemlista2 in zip(lista1, lista2):
    lista3.append(itemlista1 + itemlista2)
s1 = time.time()
print(lista1[:5])
print(lista2[:5])
print(lista3[:5])
for_time = s1 - s0
print(for_time)

[6, 3, 5, 3, 2]
[7, 10, 3, 5, 1]
[13, 13, 8, 8, 3]
2.743499517440796


In [3]:
s0 = time.time()
matrix1 = np.random.randint(1, 10, 10**6)
matrix2 = np.random.randint(1, 10, 10**6)
matrix3 = np.sum([matrix1, matrix2], axis=0)
s1 = time.time()
print(matrix1[:5])
print(matrix2[:5])
print(matrix3[:5])
np_time = s1 - s0
print(np_time)

[4 5 8 8 1]
[8 1 7 2 4]
[12  6 15 10  5]
0.07697129249572754


In [4]:
print(for_time / np_time)

35.64315251160788


In [16]:
def matrix_sum(grandeza):
    matrix1 = np.random.randint(1, 10, 10**grandeza, dtype=np.uint8)
    matrix2 = np.random.randint(1, 10, 10**grandeza, dtype=np.uint8)
    matrix3 = np.sum([matrix1, matrix2], axis=0, dtype=np.uint8)
    print("%d items" % matrix3.size)
    print("%d Kb" % ((matrix3.size * matrix3.itemsize) / 1000))
    del matrix1, matrix2, matrix3
    
for grandeza in range(2, 9):
    s0 = time.time()
    matrix_sum(grandeza)
    s1 = time.time()
    print(s1 - s0)

    

100 items
0 Kb
0.0005977153778076172
1000 items
1 Kb
0.00037097930908203125
10000 items
10 Kb
0.002354860305786133
100000 items
100 Kb
0.005045652389526367
1000000 items
1000 Kb
0.03474926948547363
10000000 items
10000 Kb
0.27954697608947754
100000000 items
100000 Kb
3.096463203430176
1000000000 items
1000000 Kb
62.20497417449951
